{
 "title": "Final_project",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Información",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Info",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# IoT Final Project - Hydroponic crop\n\n> Source code: https://github.com/gnaguerrer/server-hydroponic\n\n```\ngit clone https://github.com/gnaguerrer/server-hydroponic\ncd server-hydroponic\ndocker compose build\ndocker compose up -d\n```"
     }
    }
   ]
  },
  { "title": "Configuración", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Alertas SMS",
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 2 },
   "options": {
    "content": "Las alertas SMS se envian si se supera cualquier umbral más de tres veces."
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alert\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_value\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Predicción de temperatura promedio del dia siguiente",
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "options": {
    "content": "La temperatura de los siguientes 10 segundos se calcula teniendo en cuenta el histórico de temperatura que se obtiene en el dia actual, la cual se registra cada <#> segundos. Por otro lado, la temperatura promedio del día siguiente se calcula empleando la temperatura promedio de cada día del año. Para ambos casos se utiliza el modelo de regresión Random Forest Regressor de la librería Scikit Learn."
   }
  },
  {
   "title": "Predicciones",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"predictions\"] == \"few_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VALUE_OF_TEMP_DOME\")\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"predictions\"] == \"next_day\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MEAN_TEMP_DOME\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {}
   ]
  },
  { "title": "Tanques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"data\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura_Tanque_Principal\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"data\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura_Tanque_de_reserva\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Veces por debajo del límite inf.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_min\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MIN_TEMP_MAIN_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_min\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MIN_TEM_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura mínima",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |>  range(start: -24h)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_TEMP_MAIN_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_TEM_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Veces por encima del límite sup.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MAX_TEMP_MAIN_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MAX_TEM_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura máxima",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |>  range(start: -24h)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_TEMP_MAIN_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_TEM_TANK\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Domo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura_Domo\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura mínima y máxima",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_TEMP_DOME\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_TEMP_DOME\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Veces por debajo del límite inf.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_min\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MIN_DAY_TEMP_DOME\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_min\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MIN_NIGHT_TEMP_DOME\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Veces por encima del límite sup.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MAX_DAY_TEMP_DOME\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MAX_NIGHT_TEMP_DOME\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Plantas y medio ambiente", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"topic\"] == \"data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura_Plantas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"data\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura_medio_ambiente\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura mínima",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_TEMP_PLANTS\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_TEMP_ATM\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura máxima",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_TEMP_PLANTS\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_TEMP_ATM\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Humedad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"data\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humedad_Planta_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"data\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humedad_Planta_2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Veces por debajo del límite inf.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_min\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MIN_HUM_1\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_min\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MIN_HUM_2\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humedad mínma",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_HUM_1\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"min_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MIN_HUM_2\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Veces por encima del límite sup.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MAX_HUM_1\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"counts\"] == \"counts_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"COUNT_MAX_HUM_2\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humedad máxima",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_HUM_1\")\n  |> last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"rabbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"max_values\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAX_HUM_2\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}