FROM grafana/grafana:9.3.6

RUN grafana-cli --pluginUrl https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.23/cloudspout-button-panel.zip \
  plugins install cloudspout-button-panel